#CREATING TABLE 
CREATE TABLE PARLOUR1(
   ID INT     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL,
   STYLIST VARCHAR(100),
   SALARY         REAL
);
INSERT INTO PARLOUR1 (ID,NAME,AGE, STYLIST,SALARY)VALUES(01, 'gabriel', 18, 'HAIR STYLIST', 70000);
INSERT INTO PARLOUR1 (ID,NAME,AGE, STYLIST,SALARY)VALUES(02, 'madona', 19, 'SKIN THERAPHIST', 90000);
INSERT INTO PARLOUR1 (ID,NAME,AGE, STYLIST,SALARY)VALUES(03, 'juliet', 18, 'HAIR THERAPHIST', 80000);
INSERT INTO PARLOUR1 (ID,NAME,AGE, STYLIST,SALARY)VALUES(04, 'rossy', 19, 'SAREE DRAPIST', 60000);
INSERT INTO PARLOUR1 (ID,NAME,AGE, STYLIST,SALARY)VALUES(05, 'stephen', 18, 'BRIDAL STYLIST', 100000);
INSERT INTO PARLOUR1 (ID,NAME,AGE, STYLIST,SALARY)VALUES(06, 'glowria', 19, 'SKIN CARE', 90000);
INSERT INTO PARLOUR1 (ID,NAME,AGE, STYLIST,SALARY)VALUES(07, 'emile', 20, 'MANICURE', 80000);
INSERT INTO PARLOUR1 (ID,NAME,AGE, STYLIST,SALARY)VALUES(09, 'marie', 18, 'PEDICURE', 72000);
INSERT INTO PARLOUR1 (ID,NAME,AGE, STYLIST,SALARY)VALUES(10, 'kevin', 19, 'MASTER STYLIST', 95000);
INSERT INTO PARLOUR1 (ID,NAME,AGE, STYLIST,SALARY)VALUES(12, 'nora', 19, 'ASSISTANT STYLIST', 75000);
select *from PARLOUR1;
 

#LOGICAL OPERATIONS AND,OR,NOT
=
SELECT * FROM PARLOUR1 WHERE SALARY BETWEEN 60000 AND 80000; 
SELECT * FROM PARLOUR1 WHERE NAME = 'rossy' OR STYLIST SECTION = 'SAREE DRAPIST';  
SELECT * FROM PARLOUR1 WHERE NOT STYLIST SECTION = 'BRIDAL STYLIST';  

# CREATING ANOTHER TABLE 
CREATE TABLE PARLOUR2(
   ID INT     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL,
   BLOODGROUP          CHAR(20)    NOT NULL
);
select *from PARLOUR2;
INSERT INTO PARLOUR2 (ID,NAME,AGE,BLOODGROUP)VALUES(01, 'aadhila', 18, 'O+');
INSERT INTO PARLOUR2 (ID,NAME,AGE,BLOODGROUP)VALUES(02, 'aishwarya', 19, 'A+');
INSERT INTO PARLOUR2 (ID,NAME,AGE,BLOODGROUP)VALUES(03, 'akshaya saravanan', 18, 'O-');
INSERT INTO PARLOUR2 (ID,NAME,AGE,BLOODGROUP)VALUES(04, 'akshaya', 19, 'A+');
INSERT INTO PARLOUR2 (ID,NAME,AGE,BLOODGROUP)VALUES(05, 'madhumitha', 18, 'B+');
INSERT INTO PARLOUR2 (ID,NAME,AGE,BLOODGROUP)VALUES(06, 'keerthana', 18, 'AB+');
INSERT INTO PARLOUR2 (ID,NAME,AGE,BLOODGROUP)VALUES(07, 'karishma', 19, 'O+');
INSERT INTO PARLOUR2 (ID,NAME,AGE,BLOODGROUP)VALUES(09, 'karthiga', 18, 'B+');
INSERT INTO PARLOUR2 (ID,NAME,AGE,BLOODGROUP)VALUES(10, 'harshini', 19, 'A+');
INSERT INTO PARLOUR2 (ID,NAME,AGE,BLOODGROUP)VALUES(12, 'harini', 24, 'O+');
SELECT*FROM PARLOUR2

#MIN AND MAX

SELECT MIN(SALARY) AS MINSALARY
FROM PARLOUR1;
SELECT MAX(SALARY) AS MAXSALARY
FROM PARLOUR1;

# COUNTING THE COLUMN SECTION

SELECT COUNT(STYLIST)
FROM PARLOUR1;

#AVERAGE

SELECT AVG(SALARY)
FROM PARLOUR1;

#LEFT JOIN 

SELECT PARLOUR1.NAME,PARLOUR2.BLOODGROUP
FROM PARLOUR1
LEFT JOIN PARLOUR2
ON PARLOUR1.ID = PARLOUR2.ID;

# RIGHT JOIN

SELECT PARLOUR2.NAME,PARLOUR1.AGE
FROM PARLOUR2
RIGHT JOIN PARLOUR1
ON PARLOUR2.ID = PARLOUR1.ID;

# FULL JOIN

SELECT PARLOUR1.NAME,PARLOUR2.AGE,PARLOUR1.STYLIST,PARLOUR2.BLOODGROUP
FROM PARLOUR1
FULL OUTER JOIN PARLOUR2 ON PARLOUR2.ID = PARLOUR1.ID
ORDER BY PARLOUR1.NAME;

#UNION

SELECT NAME FROM PARLOUR1
UNION
SELECT NAME FROM PARLOUR2
ORDER BY NAME;

#SUM

SELECT SUM(SALARY)
FROM PARLOUR1;

#ASCENDING AND DESCENDING

SELECT * FROM PARLOUR1
ORDER BY NAME ASC;
SELECT * FROM PARLOUR2
ORDER BY NAME DESC;